import { eq, and, isNull, sql, ne, isNotNull } from 'drizzle-orm';
import { UserMemoryProfile } from '../agents/intent/manager/intent.manager.types';
import { HydeGeneratorAgent } from '../agents/profile/hyde/hyde.generator';
import { ProfileGenerator } from '../agents/profile/profile.generator';
import db from '../lib/db';
import { IndexEmbedder } from '../lib/embedder';
import { VectorStoreOption, VectorSearchResult, Embedder } from '../agents/common/types';
import { checkAndTriggerSocialSync } from '../lib/integrations/social-sync';
import { json2md } from '../lib/json2md/json2md';
import { log } from '../lib/log';
import { searchUser } from '../lib/parallel/parallel';
import { NotificationPreferences, User, UserSocials, userNotificationSettings, userProfiles } from '../lib/schema';

export interface UpdateProfileDto {
  name?: string;
  intro?: string;
  avatar?: string;
  location?: string;
  timezone?: string;
  socials?: UserSocials;
  notificationPreferences?: NotificationPreferences;
}

export interface GenerateProfileCallbacks {
  onStatus: (msg: string) => void;
  onResult: (data: { intro: string; location: string; intents: any[] }) => void;
  onError: (msg: string) => void;
}

/**
 * ProfileService
 * 
 * Manages the "Digital Twin" of the user.
 * 
 * CORE CONCEPTS:
 * - Identity: Name, Bio, Location (Explicitly set or inferred).
 * - Narrative: Rich text description of the user's context (Generated by AI).
 * - Attributes: Structured tags (Skills, Interests).
 * - HyDE: "Hypothetical Document Embeddings" used for advanced matching.
 * 
 * KEY RESPONSIBILITIES:
 * - Profile CRUD (Identity, Attributes, Settings).
 * - AI Generation: Triggers `ProfileGenerator` to repair/fill profile from sparse data.
 * - Intent Detection: Auto-detects intents from Bio updates.
 * - HyDE Maintenance: Regenerates HyDE embeddings when profile changes.
 */
export class ProfileService {
  private profileEmbedder: Embedder;

  constructor() {
    this.profileEmbedder = new IndexEmbedder({
      searcher: this.searchProfiles.bind(this)
    });
  }

  /**
   * Updates user profile data and triggers necessary side effects.
   * 
   * SIDE EFFECTS:
   * - If `intro` changes -> Triggers background Intent Generation + HyDE regeneration.
   * - If `socials` change -> Triggers social data sync.
   * 
   * @param userId - ID of user to update.
   * @param data - Partial update data.
   * @param updatedUser - The user object *after* core user table update.
   * @param oldUser - The user object *before* update (for diffing).
   */
  async updateProfile(userId: string, data: UpdateProfileDto, updatedUser: User, oldUser: User | null) {
    const { name, intro, location, socials, notificationPreferences } = data;

    // Upsert into 'user_profiles' table
    if (intro !== undefined || location !== undefined || name !== undefined) {
      const existingProfileRes = await db.select().from(userProfiles).where(eq(userProfiles.userId, userId)).limit(1);
      const existingIdentity = existingProfileRes[0]?.identity || { name: updatedUser.name, bio: '', location: '' };

      const newIdentity = {
        name: name || existingIdentity.name,
        bio: intro !== undefined ? intro : existingIdentity.bio,
        location: location !== undefined ? location : existingIdentity.location
      };

      await db.insert(userProfiles)
        .values({
          userId: userId,
          identity: newIdentity,
        })
        .onConflictDoUpdate({
          target: userProfiles.userId,
          set: {
            identity: newIdentity,
            updatedAt: new Date()
          }
        });

      // Trigger background intent generation if bio (intro) changed
      if (intro !== undefined) {
        // Removed: processProfileUpdateBackground called from Service -> moved to Route/Queue architecture
        // this.processProfileUpdateBackground(userId, intro, updatedUser.name);
      } else if (name !== undefined || location !== undefined) {
        // If only name/location changed, we still might want to update HyDE if profile exists
        // For now, let's keep it tied to Intro/Intent generation flow or explicit profile generation to avoid churn
      }
    }

    // Update notification preferences
    let updatedPreferences = null;
    if (notificationPreferences !== undefined) {
      const existingSettings = await db.select()
        .from(userNotificationSettings)
        .where(eq(userNotificationSettings.userId, userId))
        .limit(1);

      if (existingSettings.length > 0) {
        const settings = await db.update(userNotificationSettings)
          .set({
            preferences: notificationPreferences,
            updatedAt: new Date()
          })
          .where(eq(userNotificationSettings.userId, userId))
          .returning();
        updatedPreferences = settings[0].preferences;
      } else {
        const settings = await db.insert(userNotificationSettings)
          .values({
            userId: userId,
            preferences: notificationPreferences
          })
          .returning();
        updatedPreferences = settings[0].preferences;
      }
    } else {
      const settings = await db.select()
        .from(userNotificationSettings)
        .where(eq(userNotificationSettings.userId, userId))
        .limit(1);
      updatedPreferences = settings[0]?.preferences || {
        connectionRequest: true,
        connectionAccepted: true,
        connectionRejected: true,
        weeklyNewsletter: true,
      };
    }

    if (socials !== undefined) {
      // Check old socials to see if we need to sync
      const oldUserSocials = oldUser ? oldUser.socials : null;
      checkAndTriggerSocialSync(userId, oldUserSocials, socials);
    }

    return {
      ...updatedUser,
      notificationPreferences: updatedPreferences
    };
  }


  /**
   * Helper: Repair Profile if incomplete.
   * Internal logic exposed for Worker.
   */
  async repairProfileIfIncomplete(userId: string, intro: string, userName: string | null) {
    return this._repairProfileIfIncomplete(userId, intro, userName);
  }

  /**
   * Step 1: Repair Profile if incomplete (Private Impl).
   */
  private async _repairProfileIfIncomplete(userId: string, intro: string, userName: string | null) {
    const profileRes = await db.select().from(userProfiles).where(eq(userProfiles.userId, userId)).limit(1);
    if (!profileRes.length) return null;

    let userProfile = profileRes[0];

    // Check completeness
    const hasAttributes = userProfile.attributes &&
      ((userProfile.attributes.interests?.length || 0) > 0 || (userProfile.attributes.skills?.length || 0) > 0);
    const hasNarrative = !!userProfile.narrative;

    if (!hasAttributes || !hasNarrative) {
      log.info('[ProfileService] Profile incomplete, triggering repair via ProfileGenerator', { userId });
      const bioToUse = intro || userProfile.identity?.bio || '';

      if (bioToUse) {
        try {
          const embedder = new IndexEmbedder();
          const generator = new ProfileGenerator(embedder);
          const generated = await generator.run(bioToUse);

          const fixedIdentity = {
            ...generated.profile.identity,
            location: generated.profile.identity.location || ''
          };

          // Update DB
          await db.update(userProfiles)
            .set({
              identity: fixedIdentity,
              narrative: generated.profile.narrative,
              attributes: generated.profile.attributes,
              embedding: generated.embedding, // Use generated embedding
              updatedAt: new Date()
            })
            .where(eq(userProfiles.id, userProfile.id));

          // Return updated object
          return {
            ...userProfile,
            identity: fixedIdentity,
            narrative: generated.profile.narrative,
            attributes: generated.profile.attributes
          };

        } catch (e) {
          log.error('[ProfileService] Profile repair failed:', { error: e });
        }
      }
    }
    return userProfile;
  }

  /**
   * Helper to generate and save HyDE profile.
   * Public for Worker usage.
   */
  async generateAndSaveHydeProfile(userId: string, profile: UserMemoryProfile) {
    return this.triggerBackgroundHydeGeneration(userId, profile);
  }

  /**
   * Helper to trigger HyDE generation in the background
   */
  private async triggerBackgroundHydeGeneration(userId: string, profile: UserMemoryProfile) {
    (async () => {
      try {
        log.info('[ProfileService] Generating HyDE description and embedding...');
        const embedder = new IndexEmbedder();
        const hydeGenerator = new HydeGeneratorAgent(embedder);

        const profileContext = json2md.keyValue({
          bio: profile.identity.bio || '',
          location: profile.identity.location || '',
          interests: profile.attributes.interests || [],
          context: profile.narrative?.context || ''
        });

        const hydeResult = await hydeGenerator.generate(profileContext);

        if (hydeResult && hydeResult.description) {
          const description = hydeResult.description;
          log.info(`[ProfileService] HyDE Description Length: ${description.length} chars. Preview: "${description.substring(0, 100)}..."`);

          // Use returned embedding or generate new one
          const hydeEmbedding = (hydeResult.embedding || await embedder.generate(description)) as number[];

          await db.update(userProfiles)
            .set({
              hydeDescription: description,
              hydeEmbedding,
              updatedAt: new Date()
            })
            .where(eq(userProfiles.userId, userId));

          log.info('[ProfileService] ✅ HyDE profile updated.');
        }
      } catch (error) {
        log.error('[ProfileService] Failed to generate HyDE profile', { error });
      }
    })();
  }

  async generateProfile(user: User, callbacks: GenerateProfileCallbacks) {
    try {
      const socials = (user.socials || {}) as { x?: string; linkedin?: string; github?: string; websites?: string[] };

      callbacks.onStatus('Searching for public information...');

      const objective = {
        name: user.name || 'Unknown',
        email: user.email,
        linkedin: socials.linkedin,
        x: socials.x,
        github: socials.github,
        websites: socials.websites
      };

      const searchResult = await searchUser(objective);

      callbacks.onStatus('Analyzing profile data...');

      const markdownData = json2md.fromObject(
        searchResult.results.map(r => ({
          title: r.title,
          content: r.excerpts.join('\n')
        }))
      );
      const embedder = new IndexEmbedder();
      const generator = new ProfileGenerator(embedder);
      const result = await generator.run(markdownData);

      const fixedIdentity = {
        ...result.profile.identity,
        location: result.profile.identity.location || ''
      };

      await db.insert(userProfiles)
        .values({
          userId: user.id,
          identity: fixedIdentity,
          narrative: result.profile.narrative,
          attributes: result.profile.attributes,
          embedding: result.embedding
        })
        .onConflictDoUpdate({
          target: userProfiles.userId,
          set: {
            identity: fixedIdentity,
            narrative: result.profile.narrative,
            attributes: result.profile.attributes,
            embedding: result.embedding,
            updatedAt: new Date(),
          }
        });

      callbacks.onResult({
        intro: result.profile.identity.bio || '',
        location: result.profile.identity.location || '',
        intents: []
      });
    } catch (error) {
      callbacks.onError('Failed to generate summary');
    }
  }

  /**
   * Get profiles that do not have an embedding yet.
   */
  async getProfilesMissingEmbeddings() {
    return await db
      .select()
      .from(userProfiles)
      .where(isNull(userProfiles.embedding));
  }

  /**
   * Update the embedding for a specific user profile.
   */
  async updateProfileEmbedding(profileId: string, embedding: number[]) {
    await db.update(userProfiles)
      .set({ embedding })
      .where(eq(userProfiles.id, profileId));
  }

  /**
   * Update HyDE data for a profile.
   */
  async updateProfileHyde(profileId: string, hydeDescription: string, hydeEmbedding: number[]) {
    await db.update(userProfiles)
      .set({
        hydeDescription,
        hydeEmbedding,
        updatedAt: new Date()
      })
      .where(eq(userProfiles.id, profileId));
  }

  /**
   * Get a complete User Profile by User ID.
   */
  async getProfile(userId: string) {
    const [profile] = await db.select()
      .from(userProfiles)
      .where(eq(userProfiles.userId, userId))
      .limit(1);
    return profile;
  }

  // Get all profiles that have an embedding.
  async getAllProfilesWithEmbeddings() {
    return db.select()
      .from(userProfiles)
      .where(isNotNull(userProfiles.embedding));
  }

  /**
   * Find similar profiles using vector similarity search.
   * Excludes the source user.
   */
  async findSimilarProfiles(sourceUserId: string, embedding: number[], limit: number = 20) {
    const results = await this.profileEmbedder.search<typeof userProfiles.$inferSelect>(
      embedding,
      'profiles',
      {
        limit,
        filter: {
          userId: { ne: sourceUserId }
        }
      }
    );

    return results.map(r => ({
      ...r.item,
      score: r.score
    }));
  }


  /**
   * Public implementation of profile search.
   * Can be injected into Embedders.
   */
  async searchProfiles<T>(vector: number[], collection: string, options?: VectorStoreOption<T>): Promise<VectorSearchResult<T>[]> {
    if (collection !== 'profiles') {
      throw new Error(`ProfileService only supports 'profiles' collection, got '${collection}'`);
    }
    const limit = options?.limit || 10;
    const filter = options?.filter;
    const vectorString = JSON.stringify(vector);

    // Build conditions
    const conditions = [isNotNull(userProfiles.embedding)];

    if (filter) {
      if (filter.userId && typeof filter.userId === 'object' && filter.userId.ne) {
        conditions.push(ne(userProfiles.userId, filter.userId.ne));
      }
    }

    const whereClause = and(...conditions);

    const resultsWithDistance = await db.select({
      item: userProfiles,
      distance: sql<number>`${userProfiles.embedding} <=> ${vectorString}`
    })
      .from(userProfiles)
      .where(whereClause)
      .orderBy(sql`${userProfiles.embedding} <=> ${vectorString}`)
      .limit(limit);

    return resultsWithDistance.map((r: any) => ({
      item: r.item as unknown as T,
      score: 1 - r.distance
    }));
  }
}

export const profileService = new ProfileService();
