export const TESTABLE_TEST_ACCOUNTS = [
  {
    name: 'Seren Sandikci',
    email: 'test-1761@privy.io',
    phoneNumber: '+1 555 555 5724',
    otpCode: '888893',
    linkedin: 'https://www.linkedin.com/in/serensandikci',
    github: null as string | null,
    x: 'https://x.com/serensandikci',
    website: null as string | null,
  },
  {
    name: 'Seref Yarar',
    email: 'test-9716@privy.io',
    phoneNumber: '+1 555 555 2920',
    otpCode: '670543',
    linkedin: 'https://www.linkedin.com/in/serefyarar',
    github: 'https://github.com/serefyarar',
    x: 'https://x.com/hyperseref',
    website: null as string | null,
  },
  {
    name: 'Yanki Ekin Yüksel',
    email: 'test-6285@privy.io',
    phoneNumber: '+1 555 555 1625',
    otpCode: '607027',
    linkedin: 'https://linkedin.com/in/yanekyuk',
    github: 'https://github.com/yanekyuk',
    x: null as string | null,
    website: null as string | null,
  },
];

/** Profile payload for seed user_profiles (identity, narrative, attributes). */
export interface SeedProfile {
  identity: { name: string; bio: string; location: string };
  narrative: { context: string };
  attributes: { interests: string[]; skills: string[] };
}

/** Synthetic tester persona: account identity + profile + intents for db seed. */
export interface TesterPersona {
  name: string;
  email: string;
  linkedin?: string | null;
  github?: string | null;
  x?: string | null;
  website?: string | null;
  profile: SeedProfile;
  intents: string[];
}

/** Maximum number of tester personas that can be seeded in one run (0–78). */
export const TESTER_PERSONAS_MAX = 78;

/** 78 hand-crafted realistic tester personas for seed (deduplicated). Intents are created via intent graph. */
export const TESTER_PERSONAS: TesterPersona[] = [
  {
    name: 'Alex Chen',
    email: 'seed-tester-1@index-network.test',
    linkedin: 'https://linkedin.com/in/alexchen-dev',
    github: 'https://github.com/alexchen',
    x: null,
    website: null,
    profile: {
      identity: {
        name: 'Alex Chen',
        bio: 'Full-stack engineer focused on React and Node. Building developer tools.',
        location: 'San Francisco, CA',
      },
      narrative: { context: 'Previously at a YC startup. Now exploring co-founder opportunities.' },
      attributes: {
        interests: ['startups', 'developer tools', 'open source'],
        skills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL'],
      },
    },
    intents: [
      'Looking for a technical co-founder with React and backend experience for a B2B SaaS.',
      'I want to find someone to build an open-source developer tool with.',
    ],
  },
  {
    name: 'Jordan Lee',
    email: 'seed-tester-2@index-network.test',
    linkedin: 'https://linkedin.com/in/jordanlee-design',
    github: null,
    x: 'https://x.com/jordanleedesign',
    website: null,
    profile: {
      identity: {
        name: 'Jordan Lee',
        bio: 'Product designer with 8 years in fintech and health tech.',
        location: 'New York, NY',
      },
      narrative: { context: 'Design lead looking for a technical co-founder to ship a new product.' },
      attributes: {
        interests: ['fintech', 'health tech', 'design systems'],
        skills: ['Figma', 'UX research', 'prototyping', 'design systems'],
      },
    },
    intents: [
      'Seeking a technical co-founder to build a fintech app; I handle product and design.',
      'Looking for a developer interested in health tech and accessibility.',
    ],
  },
  {
    name: 'Sam Rivera',
    email: 'seed-tester-3@index-network.test',
    linkedin: 'https://linkedin.com/in/samrivera-ml',
    github: 'https://github.com/samrivera',
    x: null,
    website: null,
    profile: {
      identity: {
        name: 'Sam Rivera',
        bio: 'ML engineer. Previously worked on recommendation systems and NLP.',
        location: 'Austin, TX',
      },
      narrative: { context: 'Exploring AI/ML startup ideas and looking for co-founders or early team.' },
      attributes: {
        interests: ['machine learning', 'LLMs', 'recommendation systems'],
        skills: ['Python', 'PyTorch', 'vector search', 'LangChain'],
      },
    },
    intents: [
      'Looking for a co-founder with ML or data engineering background for an AI product.',
      'I want to find a product-minded founder to pair with on an LLM-based B2B tool.',
    ],
  },
  {
    name: 'Morgan Taylor',
    email: 'seed-tester-4@index-network.test',
    linkedin: null,
    github: 'https://github.com/morgantaylor',
    x: 'https://x.com/morgantaylor',
    website: 'https://morgantaylor.dev',
    profile: {
      identity: {
        name: 'Morgan Taylor',
        bio: 'Indie hacker and solo founder. Shipping small SaaS and writing about it.',
        location: 'Remote',
      },
      narrative: { context: 'Bootstrapping a second product. Open to partnerships or acquirer conversations.' },
      attributes: {
        interests: ['indie hacking', 'SaaS', 'content creation'],
        skills: ['Next.js', 'Stripe', 'SEO', 'writing'],
      },
    },
    intents: [
      'Seeking a marketing or growth co-founder for my existing SaaS.',
      'Open to talking with potential acquirers or strategic partners for my product.',
    ],
  },
  {
    name: 'Riley Kim',
    email: 'seed-tester-5@index-network.test',
    linkedin: 'https://linkedin.com/in/rileykim',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: {
        name: 'Riley Kim',
        bio: 'Product manager with background in edtech and marketplaces.',
        location: 'Seattle, WA',
      },
      narrative: { context: 'Exploring a new edtech idea and need technical and design partners.' },
      attributes: {
        interests: ['edtech', 'marketplaces', 'community'],
        skills: ['product strategy', 'roadmapping', 'user research', 'SQL'],
      },
    },
    intents: [
      'Looking for a technical co-founder for an edtech startup focused on adult learning.',
      'I want to find a designer and a developer to form a founding team for a marketplace idea.',
    ],
  },
  {
    name: 'Priya Nair',
    email: 'seed-tester-6@index-network.test',
    linkedin: 'https://linkedin.com/in/priyanair-data',
    github: 'https://github.com/priyanair',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Priya Nair', bio: 'Data engineer building reliable analytics pipelines for growth teams.', location: 'Chicago, IL' },
      narrative: { context: 'Leaving consulting to join a mission-driven startup as first data hire.' },
      attributes: { interests: ['analytics engineering', 'product metrics', 'experimentation'], skills: ['SQL', 'dbt', 'Airflow', 'BigQuery'] },
    },
    intents: ['Seeking an early-stage startup that needs a first data engineer to build analytics foundations.', 'Looking for founders tackling product-led growth who want help with experimentation and metrics.'],
  },
  {
    name: 'Noah Williams',
    email: 'seed-tester-7@index-network.test',
    linkedin: 'https://linkedin.com/in/noahw-frontend',
    github: 'https://github.com/noahwilliams',
    x: 'https://x.com/noahcodes',
    website: 'https://noahw.dev',
    profile: {
      identity: { name: 'Noah Williams', bio: 'Frontend engineer specializing in complex interfaces and performance.', location: 'Denver, CO' },
      narrative: { context: 'Interested in design-heavy products where frontend quality is a differentiator.' },
      attributes: { interests: ['frontend architecture', 'design systems', 'web performance'], skills: ['React', 'TypeScript', 'Next.js', 'Storybook'] },
    },
    intents: ['Looking for a startup team building a polished B2B dashboard product that needs a senior frontend engineer.', 'I want to collaborate with a product designer to craft a reusable design system for a new SaaS.'],
  },
  {
    name: 'Elena Petrova',
    email: 'seed-tester-8@index-network.test',
    linkedin: 'https://linkedin.com/in/elenapetrova-ai',
    github: 'https://github.com/elenapetrova',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Elena Petrova', bio: 'Applied AI researcher turning language models into production workflows.', location: 'Boston, MA' },
      narrative: { context: 'Building an AI operations toolkit and looking for technical collaborators.' },
      attributes: { interests: ['applied AI', 'agent workflows', 'evaluation tooling'], skills: ['Python', 'evaluation design', 'RAG', 'MLOps'] },
    },
    intents: ['Seeking an engineer experienced with distributed systems to co-build an AI operations platform.', 'Looking for design partners who want to pilot LLM evaluation workflows in real teams.'],
  },
  {
    name: 'Diego Alvarez',
    email: 'seed-tester-9@index-network.test',
    linkedin: 'https://linkedin.com/in/diegoalvarez-growth',
    github: null,
    x: 'https://x.com/diegoongrowth',
    website: null,
    profile: {
      identity: { name: 'Diego Alvarez', bio: 'Growth marketer with SaaS and marketplace launch experience.', location: 'Miami, FL' },
      narrative: { context: 'Joining technical founders as first GTM hire and building repeatable demand generation.' },
      attributes: { interests: ['growth loops', 'PLG', 'content distribution'], skills: ['positioning', 'paid acquisition', 'lifecycle marketing', 'analytics'] },
    },
    intents: ['Looking for technical founders with a launched product who need a growth partner for early traction.', 'Open to collaborating with B2B SaaS teams on positioning and go-to-market experiments.'],
  },
  {
    name: 'Hannah Brooks',
    email: 'seed-tester-10@index-network.test',
    linkedin: 'https://linkedin.com/in/hannahbrooks-devrel',
    github: 'https://github.com/hbrooks',
    x: 'https://x.com/hannahdevrel',
    website: null,
    profile: {
      identity: { name: 'Hannah Brooks', bio: 'Developer relations lead connecting engineers with useful tools.', location: 'Portland, OR' },
      narrative: { context: 'Exploring startup opportunities where community-led growth is core to the strategy.' },
      attributes: { interests: ['developer community', 'education', 'content'], skills: ['technical writing', 'public speaking', 'community strategy', 'APIs'] },
    },
    intents: ['Seeking a developer tools startup that needs early DevRel leadership and community building.', 'I want to partner with engineering founders who care about docs, education, and developer experience.'],
  },
  {
    name: 'Marcus Johnson',
    email: 'seed-tester-11@index-network.test',
    linkedin: 'https://linkedin.com/in/marcusjohnson-security',
    github: 'https://github.com/marcusj',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Marcus Johnson', bio: 'Security engineer focused on cloud security and compliance automation.', location: 'Atlanta, GA' },
      narrative: { context: 'Helping early startups become enterprise-ready without slowing product velocity.' },
      attributes: { interests: ['security automation', 'compliance', 'cloud infrastructure'], skills: ['AWS', 'threat modeling', 'SOC2', 'policy as code'] },
    },
    intents: ['Looking for B2B SaaS founders preparing for enterprise sales who need security guidance.', 'Seeking collaborators building tools that automate security and compliance workflows.'],
  },
  {
    name: 'Mei Lin',
    email: 'seed-tester-12@index-network.test',
    linkedin: 'https://linkedin.com/in/meilin-mobile',
    github: 'https://github.com/meilin',
    x: null,
    website: 'https://meilin.app',
    profile: {
      identity: { name: 'Mei Lin', bio: 'Mobile engineer building high-quality iOS and Android experiences.', location: 'Los Angeles, CA' },
      narrative: { context: 'Exploring consumer health and habit products with strong retention loops.' },
      attributes: { interests: ['consumer mobile', 'health tech', 'behavior design'], skills: ['Swift', 'Kotlin', 'React Native', 'mobile analytics'] },
    },
    intents: ['Seeking a product founder to build a habit-forming mobile health app with measurable outcomes.', 'Looking for designers experienced in consumer onboarding and retention for a mobile product.'],
  },
  {
    name: 'Arjun Patel',
    email: 'seed-tester-13@index-network.test',
    linkedin: 'https://linkedin.com/in/arjunpatel-finance',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Arjun Patel', bio: 'Finance operator supporting startup fundraising and planning.', location: 'New York, NY' },
      narrative: { context: 'Partnering with technical teams that need help with pricing, forecasts, and fundraising prep.' },
      attributes: { interests: ['fundraising', 'business models', 'unit economics'], skills: ['financial modeling', 'pricing strategy', 'investor relations', 'FP&A'] },
    },
    intents: ['Looking for startup founders who need a finance partner to prepare for seed fundraising.', 'Open to advising teams on pricing and unit economics for B2B SaaS launches.'],
  },
  {
    name: 'Sofia Martinez',
    email: 'seed-tester-14@index-network.test',
    linkedin: 'https://linkedin.com/in/sofiamartinez-product',
    github: null,
    x: 'https://x.com/sofiaproduct',
    website: null,
    profile: {
      identity: { name: 'Sofia Martinez', bio: 'Product leader with marketplace and trust-and-safety experience.', location: 'Mexico City, MX' },
      narrative: { context: 'Designing a creator marketplace and searching for technical co-founders.' },
      attributes: { interests: ['creator economy', 'marketplaces', 'trust and safety'], skills: ['product discovery', 'roadmapping', 'experimentation', 'operations'] },
    },
    intents: ['Seeking a backend engineer to co-found a creator marketplace with built-in trust and safety.', 'Looking for growth-minded operators interested in two-sided marketplace dynamics.'],
  },
  {
    name: "Liam O'Connor",
    email: 'seed-tester-15@index-network.test',
    linkedin: 'https://linkedin.com/in/liamoconnor-ops',
    github: 'https://github.com/liamops',
    x: null,
    website: null,
    profile: {
      identity: { name: "Liam O'Connor", bio: 'Platform engineer who scales infrastructure for high-growth products.', location: 'Dublin, IE' },
      narrative: { context: 'Interested in joining infrastructure-heavy startups as an early engineering leader.' },
      attributes: { interests: ['platform engineering', 'observability', 'reliability'], skills: ['Kubernetes', 'Terraform', 'Go', 'SRE'] },
    },
    intents: ['Looking for teams building developer or infrastructure products that need an early platform engineer.', 'Open to partnering with founders on reliability architecture before scale bottlenecks appear.'],
  },
  {
    name: 'Chloe Bennett',
    email: 'seed-tester-16@index-network.test',
    linkedin: 'https://linkedin.com/in/chloebennett-ux',
    github: null,
    x: null,
    website: 'https://chloebennett.design',
    profile: {
      identity: { name: 'Chloe Bennett', bio: 'UX researcher and service designer for public-sector digital products.', location: 'London, UK' },
      narrative: { context: 'Working on civic tech ideas that improve access to local services.' },
      attributes: { interests: ['civic tech', 'user research', 'accessibility'], skills: ['qualitative research', 'journey mapping', 'prototyping', 'service design'] },
    },
    intents: ['Seeking a technical collaborator to build civic tech tools for local government services.', 'Looking for teams who prioritize inclusive UX and accessibility from day one.'],
  },
  {
    name: 'Omar Haddad',
    email: 'seed-tester-17@index-network.test',
    linkedin: 'https://linkedin.com/in/omarhaddad-mlops',
    github: 'https://github.com/omarhaddad',
    x: 'https://x.com/omarmlops',
    website: null,
    profile: {
      identity: { name: 'Omar Haddad', bio: 'MLOps engineer productionizing model training and inference systems.', location: 'Berlin, DE' },
      narrative: { context: 'Seeking high-velocity AI teams that need reliable deployment and monitoring pipelines.' },
      attributes: { interests: ['MLOps', 'model serving', 'observability'], skills: ['Docker', 'Kubernetes', 'PyTorch', 'CI/CD'] },
    },
    intents: ['Looking for AI startups that need a founding MLOps engineer to ship models safely to production.', 'Open to collaborating with ML researchers who want robust evaluation and deployment infrastructure.'],
  },
  {
    name: 'Amina Yusuf',
    email: 'seed-tester-18@index-network.test',
    linkedin: 'https://linkedin.com/in/aminayusuf-community',
    github: null,
    x: 'https://x.com/aminacommunity',
    website: null,
    profile: {
      identity: { name: 'Amina Yusuf', bio: 'Community strategist helping mission-driven products build engaged user bases.', location: 'Lagos, NG' },
      narrative: { context: 'Building a network-focused startup and seeking technical and product collaborators.' },
      attributes: { interests: ['community growth', 'creator tools', 'social products'], skills: ['community operations', 'event design', 'content strategy', 'partnerships'] },
    },
    intents: ['Seeking a technical co-founder for a community platform focused on creator collaboration.', 'Looking for product builders who understand network effects and social product design.'],
  },
  {
    name: 'Ethan Park',
    email: 'seed-tester-19@index-network.test',
    linkedin: 'https://linkedin.com/in/ethanpark-bio',
    github: 'https://github.com/ethanparkbio',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Ethan Park', bio: 'Bioinformatics engineer turning clinical data into decision support tools.', location: 'San Diego, CA' },
      narrative: { context: 'Exploring healthcare data products and looking for regulatory-aware co-founders.' },
      attributes: { interests: ['digital health', 'clinical data', 'AI in healthcare'], skills: ['Python', 'biostatistics', 'ETL', 'healthcare data standards'] },
    },
    intents: ['Looking for a clinician-founder interested in building practical decision-support software.', 'Seeking engineers and operators experienced with healthcare compliance and privacy constraints.'],
  },
  {
    name: 'Grace Howard',
    email: 'seed-tester-20@index-network.test',
    linkedin: 'https://linkedin.com/in/gracehoward-enterprise',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Grace Howard', bio: 'Enterprise sales lead scaling B2B SaaS from first deal to repeatable pipeline.', location: 'Toronto, CA' },
      narrative: { context: 'Partnering with technical founders who need customer discovery and enterprise GTM support.' },
      attributes: { interests: ['enterprise SaaS', 'sales enablement', 'customer discovery'], skills: ['B2B sales', 'pipeline building', 'buyer research', 'GTM strategy'] },
    },
    intents: ['Seeking early-stage SaaS founders who want a partner for enterprise customer discovery and pilot deals.', 'Open to joining a startup where sales strategy and founder-led GTM are top priorities.'],
  },
  {
    name: 'Marco Velez',
    email: 'seed-tester-21@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/marcopaints',
    website: 'https://marcovelez.art',
    profile: {
      identity: { name: 'Marco Velez', bio: 'Oil painter and muralist. Focus on street art and public installations.', location: 'Mexico City, MX' },
      narrative: { context: 'Looking for collaborators on community mural projects and gallery shows.' },
      attributes: { interests: ['street art', 'muralism', 'public art', 'Latin American art'], skills: ['oil painting', 'spray paint', 'sketching', 'project coordination'] },
    },
    intents: ['Want to find other artists to do a joint mural project in my neighborhood.', 'Looking for a curator or gallery contact interested in showing my recent series.'],
  },
  {
    name: 'Jade Williams',
    email: 'seed-tester-22@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/jadeplays',
    website: null,
    profile: {
      identity: { name: 'Jade Williams', bio: 'Casual gamer and Twitch viewer. Love RPGs, cozy games, and speedruns.', location: 'Columbus, OH' },
      narrative: { context: 'Want to find a crew for regular game nights and maybe start streaming.' },
      attributes: { interests: ['RPGs', 'cozy games', 'speedruns', 'streaming'], skills: ['game discussion', 'community', 'Discord', 'stream setup'] },
    },
    intents: ['Looking for people to play co-op RPGs and indie games with on weekends.', 'Want to connect with other aspiring streamers to share tips and collab.'],
  },
  {
    name: 'Rosa Gutierrez',
    email: 'seed-tester-23@index-network.test',
    linkedin: 'https://linkedin.com/in/rosagutierrez-edu',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Rosa Gutierrez', bio: 'High school math teacher. Passionate about making algebra and geometry accessible.', location: 'Houston, TX' },
      narrative: { context: 'Looking for other educators to swap curricula and for volunteer tutoring opportunities.' },
      attributes: { interests: ['math education', 'bilingual ed', 'after-school programs'], skills: ['teaching', 'curriculum design', 'tutoring', 'parent communication'] },
    },
    intents: ['Want to find other math teachers to share lesson plans and problem sets.', 'Looking for volunteers or partners for a free weekend tutoring program.'],
  },
  {
    name: 'Derek Park',
    email: 'seed-tester-24@index-network.test',
    linkedin: null,
    github: 'https://github.com/derekpark',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Derek Park', bio: 'Computer science undergrad. Interested in systems and open source.', location: 'Ann Arbor, MI' },
      narrative: { context: 'Looking for summer internship leads and study groups for algorithms.' },
      attributes: { interests: ['algorithms', 'open source', 'hackathons'], skills: ['Python', 'C++', 'Linux', 'Git'] },
    },
    intents: ['Want to find a study group for competitive programming and interview prep.', 'Looking for internship or research opportunities in systems or infra.'],
  },
  {
    name: 'Yuki Tanaka',
    email: 'seed-tester-25@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: 'https://yukitanaka.design',
    profile: {
      identity: { name: 'Yuki Tanaka', bio: 'Visual artist and illustrator. Digital and traditional, focus on character design.', location: 'Tokyo, JP' },
      narrative: { context: 'Looking for clients and other artists for zine and convention projects.' },
      attributes: { interests: ['illustration', 'character design', 'zines', 'conventions'], skills: ['Procreate', 'Photoshop', 'ink', 'watercolor'] },
    },
    intents: ['Want to find artists to collaborate on a small zine or art book.', 'Looking for indie game devs who need character art or concept work.'],
  },
  {
    name: 'Marcus Johnson',
    email: 'seed-tester-26@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/marcus_runs',
    website: null,
    profile: {
      identity: { name: 'Marcus Johnson', bio: 'Recreational runner and marathoner. Coach for a local youth track club.', location: 'Atlanta, GA' },
      narrative: { context: 'Looking for running buddies and people interested in youth coaching.' },
      attributes: { interests: ['long-distance running', 'marathons', 'youth sports', 'trail running'], skills: ['running', 'coaching', 'race planning', 'injury prevention'] },
    },
    intents: ['Want to find training partners for weekend long runs and race prep.', 'Looking for volunteers or co-coaches for our youth track program.'],
  },
  {
    name: 'Fatima Hassan',
    email: 'seed-tester-27@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Fatima Hassan', bio: 'PhD student in comparative literature. Research focus on diaspora and translation.', location: 'New York, NY' },
      narrative: { context: 'Looking for writing groups and academic collaboration; open to literary translation projects.' },
      attributes: { interests: ['comparative literature', 'translation', 'diaspora', 'publishing'], skills: ['research', 'writing', 'Arabic', 'French'] },
    },
    intents: ['Want to find a writing accountability group or thesis support circle.', 'Looking for editors or translators interested in diaspora literature.'],
  },
  {
    name: 'Leo Torres',
    email: 'seed-tester-28@index-network.test',
    linkedin: null,
    github: 'https://github.com/leotorres',
    x: 'https://x.com/leogames',
    website: null,
    profile: {
      identity: { name: 'Leo Torres', bio: 'Aspiring game developer. Making small games in Unity; love narrative and puzzle games.', location: 'Austin, TX' },
      narrative: { context: 'Looking for other indie devs for game jams and feedback; want to ship my first game.' },
      attributes: { interests: ['game dev', 'Unity', 'narrative games', 'game jams'], skills: ['Unity', 'C#', 'pixel art', 'game design'] },
    },
    intents: ['Want to find a team for the next Global Game Jam or Ludum Dare.', 'Looking for playtesters and other indie devs to swap feedback with.'],
  },
  {
    name: 'Claire Dubois',
    email: 'seed-tester-29@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: 'https://clairedubois-music.com',
    profile: {
      identity: { name: 'Claire Dubois', bio: 'Singer-songwriter and guitarist. Playing folk and indie; recording first EP.', location: 'Paris, FR' },
      narrative: { context: 'Looking for a producer, session musicians, and venues for small gigs.' },
      attributes: { interests: ['folk', 'indie', 'songwriting', 'live performance'], skills: ['guitar', 'vocals', 'songwriting', 'home recording'] },
    },
    intents: ['Want to find a producer or engineer to help finish my EP.', 'Looking for other musicians to form a small band or do duo shows.'],
  },
  {
    name: 'Lucy Chen',
    email: 'seed-tester-30@index-network.test',
    linkedin: 'https://linkedin.com/in/lucychen-operations',
    github: null,
    x: 'https://x.com/lucyops',
    website: null,
    profile: {
      identity: { name: 'Lucy Chen', bio: 'Operations and launch lead for marketplaces and two-sided platforms.', location: 'Singapore, SG' },
      narrative: { context: 'Exploring a marketplace idea in APAC and need product and engineering partners.' },
      attributes: { interests: ['marketplaces', 'supply-demand', 'launch strategy'], skills: ['operations', 'partnerships', 'analytics', 'experimentation'] },
    },
    intents: ['Seeking technical and product co-founders for a niche marketplace in APAC.', 'Looking for operators with marketplace or platform experience.'],
  },
  {
    name: 'David Kim',
    email: 'seed-tester-31@index-network.test',
    linkedin: 'https://linkedin.com/in/davidkim-ai',
    github: 'https://github.com/davidkimai',
    x: null,
    website: null,
    profile: {
      identity: { name: 'David Kim', bio: 'AI/ML researcher turned builder; focused on LLM applications.', location: 'Seattle, WA' },
      narrative: { context: 'Building an LLM-powered workflow product and looking for a design or GTM co-founder.' },
      attributes: { interests: ['LLMs', 'agents', 'productivity'], skills: ['Python', 'LangChain', 'prompt engineering', 'evaluation'] },
    },
    intents: ['Looking for a design or product co-founder for an LLM-based productivity tool.', 'Seeking GTM or sales co-founder for an AI-native B2B product.'],
  },
  {
    name: 'Fatima Al-Hassan',
    email: 'seed-tester-32@index-network.test',
    linkedin: 'https://linkedin.com/in/fatimaalhassan',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Fatima Al-Hassan', bio: 'Legal and compliance lead for fintech and regulated products.', location: 'Dubai, AE' },
      narrative: { context: 'Interested in joining a fintech or regulated startup as first legal/compliance hire.' },
      attributes: { interests: ['fintech regulation', 'compliance', 'licensing'], skills: ['regulatory strategy', 'contracts', 'KYC/AML', 'policy'] },
    },
    intents: ['Seeking fintech founders who need a compliance and legal co-founder or early hire.', 'Open to advising or joining teams preparing for regulated markets.'],
  },
  {
    name: 'Tomáš Novák',
    email: 'seed-tester-33@index-network.test',
    linkedin: 'https://linkedin.com/in/tomasnovak-backend',
    github: 'https://github.com/tnovak',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Tomáš Novák', bio: 'Backend engineer with real-time and gaming infrastructure experience.', location: 'Prague, CZ' },
      narrative: { context: 'Exploring real-time collaboration or gaming infrastructure ideas.' },
      attributes: { interests: ['real-time systems', 'WebSockets', 'game backends'], skills: ['Go', 'Redis', 'WebRTC', 'scaling'] },
    },
    intents: ['Looking for a co-founder to build a real-time collaboration or multiplayer product.', 'Seeking product or game designers for a real-time infrastructure tool.'],
  },
  {
    name: 'Maya Okonkwo',
    email: 'seed-tester-34@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Maya Okonkwo', bio: 'Yoga instructor and mindfulness coach. Teaching at studios and online.', location: 'Austin, TX' },
      narrative: { context: 'Want to find other instructors for retreats and a possible small wellness collective.' },
      attributes: { interests: ['yoga', 'meditation', 'wellness', 'retreats'], skills: ['vinyasa', 'yin', 'breathwork', 'workshop facilitation'] },
    },
    intents: ['Looking for other yoga or wellness teachers to organize a weekend retreat.', 'Want to connect with people interested in starting a small mindfulness collective.'],
  },
  {
    name: 'Kenji Yamamoto',
    email: 'seed-tester-35@index-network.test',
    linkedin: 'https://linkedin.com/in/kenjiyamamoto',
    github: 'https://github.com/kenjiy',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Kenji Yamamoto', bio: 'iOS and Apple platform engineer with 10+ years experience.', location: 'Osaka, JP' },
      narrative: { context: 'Exploring consumer or productivity apps on Apple platforms.' },
      attributes: { interests: ['iOS', 'SwiftUI', 'Apple ecosystem'], skills: ['Swift', 'SwiftUI', 'Combine', 'App Store'] },
    },
    intents: ['Looking for a product or design co-founder for a native iOS app.', 'Seeking founders building premium or subscription iOS products.'],
  },
  {
    name: 'Layla Hassan',
    email: 'seed-tester-36@index-network.test',
    linkedin: 'https://linkedin.com/in/laylahassan-product',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Layla Hassan', bio: 'Product manager with deep experience in e-commerce and conversion.', location: 'Cairo, EG' },
      narrative: { context: 'Validating an e-commerce or conversion tool idea for emerging markets.' },
      attributes: { interests: ['e-commerce', 'conversion', 'checkout'], skills: ['A/B testing', 'funnels', 'analytics', 'roadmapping'] },
    },
    intents: ['Seeking technical co-founder for an e-commerce or conversion optimization product.', 'Looking for growth or marketing partners with e-commerce experience.'],
  },
  {
    name: 'Oscar Lindqvist',
    email: 'seed-tester-37@index-network.test',
    linkedin: 'https://linkedin.com/in/oscarlindqvist',
    github: 'https://github.com/oscarl',
    x: null,
    website: 'https://oscarlindqvist.se',
    profile: {
      identity: { name: 'Oscar Lindqvist', bio: 'Full-stack engineer with focus on developer experience and tooling.', location: 'Stockholm, SE' },
      narrative: { context: 'Building a devtool and looking for a growth or community co-founder.' },
      attributes: { interests: ['developer tools', 'DX', 'documentation'], skills: ['TypeScript', 'Node', 'React', 'technical writing'] },
    },
    intents: ['Looking for a DevRel or growth co-founder for a developer-focused product.', 'Seeking technical writers or community builders for a devtool.'],
  },
  {
    name: 'Rebecca Foster',
    email: 'seed-tester-38@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: 'https://rebeccafoster.art',
    profile: {
      identity: { name: 'Rebecca Foster', bio: 'Fiction writer and essayist. Working on a first novel and short stories.', location: 'Boston, MA' },
      narrative: { context: 'Looking for a critique group and potential beta readers; interested in literary journals.' },
      attributes: { interests: ['literary fiction', 'essays', 'publishing', 'writing groups'], skills: ['fiction', 'editing', 'feedback', 'submissions'] },
    },
    intents: ['Want to find a small critique group for literary fiction and essays.', 'Looking for beta readers or editors for my novel draft.'],
  },
  {
    name: 'Hassan Ali',
    email: 'seed-tester-39@index-network.test',
    linkedin: 'https://linkedin.com/in/hassanali-data',
    github: 'https://github.com/hassanali',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Hassan Ali', bio: 'Data scientist building predictive models and experimentation platforms.', location: 'Karachi, PK' },
      narrative: { context: 'Looking for a startup that needs a founding data scientist for product and growth.' },
      attributes: { interests: ['experimentation', 'causal inference', 'predictive modeling'], skills: ['Python', 'statistics', 'A/B testing', 'SQL'] },
    },
    intents: ['Seeking product or growth co-founder for a data-heavy or experimentation product.', 'Looking for startups that want to invest in data science from day one.'],
  },
  {
    name: 'Isabella Romano',
    email: 'seed-tester-40@index-network.test',
    linkedin: 'https://linkedin.com/in/isabellaromano',
    github: null,
    x: 'https://x.com/isabellaromano',
    website: null,
    profile: {
      identity: { name: 'Isabella Romano', bio: 'Partnerships and biz dev lead for SaaS and platforms.', location: 'Milan, IT' },
      narrative: { context: 'Interested in joining a B2B or platform company as first partnerships hire.' },
      attributes: { interests: ['partnerships', 'integrations', 'channel'], skills: ['negotiation', 'pipeline', 'alliances', 'GTM'] },
    },
    intents: ['Seeking B2B or platform founders who need a partnerships and biz dev co-founder.', 'Open to joining early to build partnership strategy and first deals.'],
  },
  {
    name: 'Nathan Brooks',
    email: 'seed-tester-41@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Nathan Brooks', bio: 'Volunteer coordinator for a community food bank. Organizing drives and delivery.', location: 'Washington, DC' },
      narrative: { context: 'Looking for more volunteers and partnerships with local businesses and schools.' },
      attributes: { interests: ['food security', 'community organizing', 'volunteering'], skills: ['coordination', 'scheduling', 'outreach', 'logistics'] },
    },
    intents: ['Want to find more volunteers for weekend food distribution and packing.', 'Looking for local businesses or groups to partner on donation drives.'],
  },
  {
    name: 'Sana Jamil',
    email: 'seed-tester-42@index-network.test',
    linkedin: 'https://linkedin.com/in/sanajamil',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Sana Jamil', bio: 'Recruiting and talent lead for engineering and product teams.', location: 'Toronto, CA' },
      narrative: { context: 'Want to join an early-stage startup as first recruiting hire or talent co-founder.' },
      attributes: { interests: ['technical recruiting', 'employer brand', 'hiring processes'], skills: ['sourcing', 'interviews', 'offer negotiation', 'DEI'] },
    },
    intents: ['Seeking founders who want to build a strong engineering culture and hiring process.', 'Open to talent or people ops co-founder roles at early-stage.'],
  },
  {
    name: 'Lars Eriksen',
    email: 'seed-tester-43@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: 'https://larseriksen-pottery.com',
    profile: {
      identity: { name: 'Lars Eriksen', bio: 'Potter and ceramicist. Making functional stoneware and teaching weekend workshops.', location: 'Copenhagen, DK' },
      narrative: { context: 'Looking for gallery or shop consignment and other potters to share kiln space.' },
      attributes: { interests: ['ceramics', 'pottery', 'workshops', 'craft fairs'], skills: ['wheel throwing', 'glazing', 'kiln firing', 'teaching'] },
    },
    intents: ['Want to find other potters to share studio or kiln space and materials.', 'Looking for shops or galleries interested in consignment or wholesale.'],
  },
  {
    name: 'Yolanda Mendez',
    email: 'seed-tester-44@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/yolandamendez',
    website: null,
    profile: {
      identity: { name: 'Yolanda Mendez', bio: 'High school senior. Into photography, yearbook, and maybe studying design or media.', location: 'Barcelona, ES' },
      narrative: { context: 'Looking for portfolio feedback and advice on art or design programs.' },
      attributes: { interests: ['photography', 'design', 'yearbook', 'college apps'], skills: ['photo editing', 'layout', 'social media', 'writing'] },
    },
    intents: ['Want to find other students or mentors to get feedback on my portfolio.', 'Looking for advice on design schools or media programs in Europe.'],
  },
  {
    name: 'Dmitri Volkov',
    email: 'seed-tester-45@index-network.test',
    linkedin: 'https://linkedin.com/in/dmitrivolkov',
    github: 'https://github.com/dvolkov',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Dmitri Volkov', bio: 'Backend engineer with distributed systems and database experience.', location: 'Amsterdam, NL' },
      narrative: { context: 'Interested in database, caching, or data infrastructure startups.' },
      attributes: { interests: ['databases', 'distributed systems', 'performance'], skills: ['PostgreSQL', 'Rust', 'Kafka', 'scaling'] },
    },
    intents: ['Looking for a co-founder to build a database or data infrastructure product.', 'Seeking product-minded engineers in data or infra.'],
  },
  {
    name: 'Aisha Okeke',
    email: 'seed-tester-46@index-network.test',
    linkedin: 'https://linkedin.com/in/aishaokeke',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Aisha Okeke', bio: 'Primary school teacher. Focus on reading and literacy programs.', location: 'Nairobi, KE' },
      narrative: { context: 'Looking for other teachers to share resources and for NGO or library partnerships.' },
      attributes: { interests: ['literacy', 'K-12', 'reading programs', 'community'], skills: ['teaching', 'lesson plans', 'parent engagement', 'workshops'] },
    },
    intents: ['Want to find other teachers or NGOs to collaborate on a reading challenge.', 'Looking for book donors or library partners for our school.'],
  },
  {
    name: 'Brandon Wu',
    email: 'seed-tester-47@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/brandonlifts',
    website: null,
    profile: {
      identity: { name: 'Brandon Wu', bio: 'Powerlifter and strength coach. Competing locally and coaching beginners.', location: 'Vancouver, CA' },
      narrative: { context: 'Looking for training partners and people interested in starting a small strength club.' },
      attributes: { interests: ['powerlifting', 'strength training', 'nutrition', 'competition'], skills: ['programming', 'coaching', 'form check', 'recovery'] },
    },
    intents: ['Want to find a training partner or small group for consistent lifting.', 'Looking for others interested in forming an informal strength or powerlifting club.'],
  },
  {
    name: 'Eva Schmidt',
    email: 'seed-tester-48@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/evastreams',
    website: null,
    profile: {
      identity: { name: 'Eva Schmidt', bio: 'Twitch streamer and content creator. Variety streamer, mostly FPS and horror.', location: 'Berlin, DE' },
      narrative: { context: 'Want to find other streamers for collabs and grow a small community.' },
      attributes: { interests: ['streaming', 'FPS', 'horror games', 'content creation'], skills: ['OBS', 'Discord', 'community mod', 'scheduling'] },
    },
    intents: ['Looking for other streamers to do co-streams or collab events.', 'Want to connect with viewers or mods interested in building the community.'],
  },
  {
    name: 'Carlos Mendoza',
    email: 'seed-tester-49@index-network.test',
    linkedin: 'https://linkedin.com/in/carlosmendoza',
    github: 'https://github.com/cmendoza',
    x: 'https://x.com/carlosmendoza',
    website: null,
    profile: {
      identity: { name: 'Carlos Mendoza', bio: 'Full-stack engineer with e-commerce and checkout experience.', location: 'Madrid, ES' },
      narrative: { context: 'Building a checkout or payments product and need design and GTM partners.' },
      attributes: { interests: ['e-commerce', 'payments', 'conversion'], skills: ['Node.js', 'React', 'Stripe', 'optimization'] },
    },
    intents: ['Seeking design and GTM co-founders for a checkout or payments product.', 'Looking for e-commerce or fintech founders to collaborate with.'],
  },
  {
    name: 'Jasmine Liu',
    email: 'seed-tester-50@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Jasmine Liu', bio: 'Grad student in environmental policy. Research on climate adaptation and local gov.', location: 'Sydney, AU' },
      narrative: { context: 'Looking for research collaborators and NGOs or agencies for internship or fieldwork.' },
      attributes: { interests: ['climate policy', 'adaptation', 'local government', 'NGOs'], skills: ['research', 'policy analysis', 'writing', 'data'] },
    },
    intents: ['Want to find other grad students or researchers working on adaptation policy.', 'Looking for NGOs or government contacts for fieldwork or internships.'],
  },
  {
    name: "Ryan O'Brien",
    email: 'seed-tester-51@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: "Ryan O'Brien", bio: 'Retired history teacher. Tutoring part-time and volunteering at a local museum.', location: 'Philadelphia, PA' },
      narrative: { context: 'Looking for other retirees or volunteers for history education and museum outreach.' },
      attributes: { interests: ['history', 'tutoring', 'museums', 'volunteering'], skills: ['teaching', 'research', 'presentation', 'mentoring'] },
    },
    intents: ['Want to find other volunteers for the museum education program.', 'Looking for tutoring or mentoring opportunities with high school students.'],
  },
  {
    name: 'Nadia Petrov',
    email: 'seed-tester-52@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Nadia Petrov', bio: 'Chef and recipe developer. Running a small supper club and writing a cookbook.', location: 'Kyiv, UA' },
      narrative: { context: 'Looking for collaborators for pop-up dinners and a possible food blog or newsletter.' },
      attributes: { interests: ['cooking', 'supper clubs', 'cookbook', 'local ingredients'], skills: ['recipe development', 'menu planning', 'catering', 'food styling'] },
    },
    intents: ['Want to find other chefs or hosts for a joint pop-up or supper club series.', 'Looking for a photographer or writer to collaborate on the cookbook.'],
  },
  {
    name: 'Kwame Asante',
    email: 'seed-tester-53@index-network.test',
    linkedin: 'https://linkedin.com/in/kwameasante',
    github: null,
    x: 'https://x.com/kwameasante',
    website: null,
    profile: {
      identity: { name: 'Kwame Asante', bio: 'Sales development and outbound lead for B2B SaaS.', location: 'Accra, GH' },
      narrative: { context: 'Want to join an early-stage B2B company to build outbound and SDR motion.' },
      attributes: { interests: ['outbound', 'SDR', 'pipeline'], skills: ['outreach', 'CRM', 'qualification', 'pipeline management'] },
    },
    intents: ['Seeking B2B founders who need a sales development co-founder or first hire.', 'Looking for teams ready to scale outbound and pipeline.'],
  },
  {
    name: 'Ingrid Bergstrom',
    email: 'seed-tester-54@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Ingrid Bergstrom', bio: 'Poet and spoken word artist. Performing at open mics and submitting to journals.', location: 'Oslo, NO' },
      narrative: { context: 'Looking for a writing group and venues or festivals for performance.' },
      attributes: { interests: ['poetry', 'spoken word', 'performance', 'publishing'], skills: ['writing', 'performance', 'editing', 'workshop facilitation'] },
    },
    intents: ['Want to find a poetry critique group or open mic community.', 'Looking for venues or festivals interested in spoken word or poetry events.'],
  },
  {
    name: 'Vlad Petrescu',
    email: 'seed-tester-55@index-network.test',
    linkedin: 'https://linkedin.com/in/vladpetrescu',
    github: 'https://github.com/vpetrescu',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Vlad Petrescu', bio: 'Frontend architect with focus on performance and accessibility.', location: 'Bucharest, RO' },
      narrative: { context: 'Interested in products where frontend quality drives conversion and retention.' },
      attributes: { interests: ['performance', 'accessibility', 'frontend architecture'], skills: ['React', 'performance', 'a11y', 'Core Web Vitals'] },
    },
    intents: ['Looking for a backend or product co-founder for a frontend-heavy product.', 'Seeking teams that prioritize performance and accessibility.'],
  },
  {
    name: 'Marta Kowalczyk',
    email: 'seed-tester-56@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Marta Kowalczyk', bio: 'Family caregiver. Supporting an aging parent; interested in respite and support groups.', location: 'Krakow, PL' },
      narrative: { context: 'Looking for local caregiver support and resources; open to part-time remote work later.' },
      attributes: { interests: ['caregiving', 'elder care', 'support groups', 'wellness'], skills: ['advocacy', 'scheduling', 'health coordination', 'communication'] },
    },
    intents: ['Want to find a local caregiver support group or respite options.', 'Looking for others in similar situations to share resources and advice.'],
  },
  {
    name: 'Jake Morrison',
    email: 'seed-tester-57@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Jake Morrison', bio: 'Tabletop RPG player and DM. Running D&D and other systems; love worldbuilding.', location: 'Nashville, TN' },
      narrative: { context: 'Looking for a steady group and maybe co-DMs for one-shots or campaigns.' },
      attributes: { interests: ['D&D', 'TTRPGs', 'worldbuilding', 'board games'], skills: ['DMing', 'storytelling', 'rules', 'scheduling'] },
    },
    intents: ['Want to find players for a new campaign or one-shots.', 'Looking for other DMs to swap ideas and maybe co-run events.'],
  },
  {
    name: 'Leila Abbas',
    email: 'seed-tester-58@index-network.test',
    linkedin: 'https://linkedin.com/in/leilaabbas',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Leila Abbas', bio: 'Product designer with focus on onboarding and activation.', location: 'Amman, JO' },
      narrative: { context: 'Exploring a product idea where onboarding is the key differentiator.' },
      attributes: { interests: ['onboarding', 'activation', 'product-led growth'], skills: ['Figma', 'user flows', 'experimentation', 'analytics'] },
    },
    intents: ['Seeking technical co-founder for a product where onboarding and activation are core.', 'Looking for growth or engineering partners who care about first-time UX.'],
  },
  {
    name: 'Tyler Reed',
    email: 'seed-tester-59@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/tylerrides',
    website: null,
    profile: {
      identity: { name: 'Tyler Reed', bio: 'Cyclist and bike advocate. Group rides, commuting, and local advocacy.', location: 'Phoenix, AZ' },
      narrative: { context: 'Looking for ride buddies and people interested in bike advocacy or events.' },
      attributes: { interests: ['cycling', 'group rides', 'bike advocacy', 'commuting'], skills: ['route planning', 'mechanical basics', 'organizing', 'advocacy'] },
    },
    intents: ['Want to find a regular group for weekend rides or commuting.', 'Looking for others interested in local bike advocacy or event organizing.'],
  },
  {
    name: 'Sara Nilsson',
    email: 'seed-tester-60@index-network.test',
    linkedin: 'https://linkedin.com/in/saranilsson',
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Sara Nilsson', bio: 'Product operations and tooling lead for product teams.', location: 'Gothenburg, SE' },
      narrative: { context: 'Building product ops tooling and looking for technical and design partners.' },
      attributes: { interests: ['product ops', 'roadmapping', 'tooling'], skills: ['Jira', 'Notion', 'analytics', 'process design'] },
    },
    intents: ['Seeking engineering co-founder for a product ops or roadmapping tool.', 'Looking for PMs or designers interested in product operations.'],
  },
  // Personas 61–78: mixed artists, gamers, educators, students, athletes, and professionals
  {
    name: 'Zara Khan',
    email: 'seed-tester-61@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: 'https://zarakhan.art',
    profile: {
      identity: { name: 'Zara Khan', bio: 'Digital artist and animator. Character design and short loops for social.', location: 'London, UK' },
      narrative: { context: 'Looking for clients and other artists for collabs and zines.' },
      attributes: { interests: ['digital art', 'animation', 'character design', 'social media'], skills: ['Procreate', 'After Effects', 'illustration', 'storyboarding'] },
    },
    intents: ['Want to find artists for a collaborative zine or animation project.', 'Looking for clients who need character design or short-form animation.'],
  },
  {
    name: 'Andre Santos',
    email: 'seed-tester-62@index-network.test',
    linkedin: 'https://linkedin.com/in/andresantos-sre',
    github: 'https://github.com/andresantos',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Andre Santos', bio: 'SRE and DevOps engineer with multi-cloud experience.', location: 'São Paulo, BR' },
      narrative: { context: 'Interested in joining an early-stage infra or platform company.' },
      attributes: { interests: ['reliability', 'cost optimization', 'observability'], skills: ['Kubernetes', 'Terraform', 'GCP', 'Datadog'] },
    },
    intents: ['Looking for a startup that needs a founding SRE to build reliability from day one.', 'Open to platform or infra startups with strong technical founders.'],
  },
  {
    name: 'Priya Nair',
    email: 'seed-tester-63@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Priya Nair', bio: 'Graduate student in neuroscience. Research on memory and aging.', location: 'Boston, MA' },
      narrative: { context: 'Looking for lab collaborations and postdoc or industry options.' },
      attributes: { interests: ['neuroscience', 'memory', 'aging', 'research'], skills: ['data analysis', 'Python', 'writing', 'presentations'] },
    },
    intents: ['Want to find other grad students or postdocs for journal clubs and collaboration.', 'Looking for industry or postdoc opportunities in neuro or biotech.'],
  },
  {
    name: 'Felix Weber',
    email: 'seed-tester-64@index-network.test',
    linkedin: 'https://linkedin.com/in/felixweber-dev',
    github: 'https://github.com/felixweber',
    x: null,
    website: 'https://felixweber.dev',
    profile: {
      identity: { name: 'Felix Weber', bio: 'Software engineer with focus on Rust and systems programming.', location: 'Munich, DE' },
      narrative: { context: 'Exploring performance-critical or systems-level product ideas.' },
      attributes: { interests: ['systems programming', 'performance', 'open source'], skills: ['Rust', 'C++', 'Linux', 'benchmarking'] },
    },
    intents: ['Looking for a co-founder to build a devtool or infrastructure product in Rust.', 'Seeking product-minded engineers interested in systems and performance.'],
  },
  {
    name: 'Nina Kowalski',
    email: 'seed-tester-65@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Nina Kowalski', bio: 'Soccer coach for youth teams. Former semi-pro player; now coaching and refereeing.', location: 'Warsaw, PL' },
      narrative: { context: 'Looking for assistant coaches and tournament or league connections.' },
      attributes: { interests: ['soccer', 'youth sports', 'coaching', 'refereeing'], skills: ['coaching', 'tactics', 'fitness', 'parent communication'] },
    },
    intents: ['Want to find an assistant coach or volunteers for our youth team.', 'Looking for other coaches to share drills and tournament info.'],
  },
  {
    name: 'Raj Mehta',
    email: 'seed-tester-66@index-network.test',
    linkedin: 'https://linkedin.com/in/rajmehta-ml',
    github: 'https://github.com/rajmehta',
    x: 'https://x.com/rajml',
    website: null,
    profile: {
      identity: { name: 'Raj Mehta', bio: 'ML engineer focused on computer vision and edge deployment.', location: 'Hyderabad, IN' },
      narrative: { context: 'Exploring vertical AI applications in retail and logistics.' },
      attributes: { interests: ['computer vision', 'edge ML', 'retail tech'], skills: ['Python', 'PyTorch', 'ONNX', 'TensorFlow Lite'] },
    },
    intents: ['Seeking a domain expert co-founder in retail or logistics for an AI product.', 'Looking for engineers with embedded or mobile ML experience.'],
  },
  {
    name: 'Vikram Sharma',
    email: 'seed-tester-67@index-network.test',
    linkedin: 'https://linkedin.com/in/vikramsharma-backend',
    github: 'https://github.com/vsharma',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Vikram Sharma', bio: 'Backend engineer building scalable APIs and event-driven systems.', location: 'Bangalore, IN' },
      narrative: { context: 'Looking for a product-focused co-founder to build developer-facing infrastructure.' },
      attributes: { interests: ['distributed systems', 'API design', 'event sourcing'], skills: ['Go', 'PostgreSQL', 'Kafka', 'gRPC'] },
    },
    intents: ['Seeking a technical co-founder with frontend or product background for an API-first startup.', 'Want to meet founders building in devtools or infrastructure.'],
  },
  {
    name: 'Elena Petrova',
    email: 'seed-tester-68@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Elena Petrova', bio: 'Classical pianist and piano teacher. Performing locally and teaching kids and adults.', location: 'Boston, MA' },
      narrative: { context: 'Looking for duet partners, accompanists, and more students.' },
      attributes: { interests: ['classical piano', 'teaching', 'performance', 'chamber music'], skills: ['piano', 'sight-reading', 'pedagogy', 'accompanying'] },
    },
    intents: ['Want to find a duet partner or accompanist for recitals.', 'Looking for referrals or partnerships with schools for piano students.'],
  },
  {
    name: 'Noah Williams',
    email: 'seed-tester-69@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/noahclimbs',
    website: null,
    profile: {
      identity: { name: 'Noah Williams', bio: 'Rock climber and boulderer. Indoor and outdoor; interested in trip planning.', location: 'Denver, CO' },
      narrative: { context: 'Looking for climbing partners and groups for weekend outdoor trips.' },
      attributes: { interests: ['rock climbing', 'bouldering', 'outdoor', 'gym climbing'], skills: ['belaying', 'route reading', 'trip planning', 'safety'] },
    },
    intents: ['Want to find regular climbing partners for gym and outdoor days.', 'Looking for a group to plan a weekend climbing trip.'],
  },
  {
    name: 'Sofia Martinez',
    email: 'seed-tester-70@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Sofia Martinez', bio: 'Dance teacher and choreographer. Ballet and contemporary; teaching kids and adults.', location: 'Mexico City, MX' },
      narrative: { context: 'Looking for guest teachers and performance or competition opportunities.' },
      attributes: { interests: ['ballet', 'contemporary', 'choreography', 'teaching'], skills: ['choreography', 'teaching', 'staging', 'costuming'] },
    },
    intents: ['Want to find guest teachers or collaborators for a summer intensive.', 'Looking for performance or competition opportunities for my students.'],
  },
  {
    name: 'Kai Nakamura',
    email: 'seed-tester-71@index-network.test',
    linkedin: null,
    github: null,
    x: 'https://x.com/kaigaming',
    website: null,
    profile: {
      identity: { name: 'Kai Nakamura', bio: 'Competitive esports player. Competing in fighting games and FPS at regional level.', location: 'Tokyo, JP' },
      narrative: { context: 'Looking for a team or training partners and potential sponsors.' },
      attributes: { interests: ['esports', 'fighting games', 'FPS', 'tournaments'], skills: ['competition', 'VOD review', 'practice routines', 'mental game'] },
    },
    intents: ['Want to find a team or regular training partners for competitive play.', 'Looking for sponsors or orgs interested in fighting game or FPS players.'],
  },
  {
    name: 'Zoe Turner',
    email: 'seed-tester-72@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Zoe Turner', bio: 'Librarian and literacy advocate. Running programs for kids and adults.', location: 'Minneapolis, MN' },
      narrative: { context: 'Looking for partners for reading programs and grant or volunteer support.' },
      attributes: { interests: ['literacy', 'libraries', 'reading programs', 'community'], skills: ['program design', 'outreach', 'grant writing', 'event planning'] },
    },
    intents: ['Want to find partners for a summer reading challenge or author visit series.', 'Looking for volunteers or grant writers to expand our programs.'],
  },
  {
    name: 'Ravi Singh',
    email: 'seed-tester-73@index-network.test',
    linkedin: 'https://linkedin.com/in/ravisingh',
    github: 'https://github.com/ravisingh',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Ravi Singh', bio: 'Backend engineer with focus on real-time and messaging systems.', location: 'Bangalore, IN' },
      narrative: { context: 'Interested in chat, collaboration, or real-time product ideas.' },
      attributes: { interests: ['real-time', 'messaging', 'WebSockets', 'scaling'], skills: ['Go', 'Redis', 'PostgreSQL', 'event-driven'] },
    },
    intents: ['Looking for a product or frontend co-founder for a real-time or messaging product.', 'Seeking teams building collaboration or communication tools.'],
  },
  {
    name: 'Simon Wright',
    email: 'seed-tester-74@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Simon Wright', bio: 'Wildlife photographer. Focus on birds and conservation; selling prints and leading tours.', location: 'Cape Town, ZA' },
      narrative: { context: 'Looking for tour partners and galleries or shops for prints.' },
      attributes: { interests: ['wildlife', 'birds', 'conservation', 'tours'], skills: ['photography', 'editing', 'tour leading', 'print sales'] },
    },
    intents: ['Want to find a partner to co-lead birding or wildlife tours.', 'Looking for galleries or shops interested in prints or licensing.'],
  },
  {
    name: 'Nadia Petrov',
    email: 'seed-tester-75@index-network.test',
    linkedin: 'https://linkedin.com/in/nadiapetrov',
    github: 'https://github.com/npetrov',
    x: null,
    website: null,
    profile: {
      identity: { name: 'Nadia Petrov', bio: 'QA and test automation engineer for web and mobile products.', location: 'Kyiv, UA' },
      narrative: { context: 'Interested in joining a product team that values quality and automation.' },
      attributes: { interests: ['test automation', 'quality', 'CI/CD'], skills: ['Playwright', 'Jest', 'Selenium', 'test strategy'] },
    },
    intents: ['Seeking early-stage teams that want a founding QA or quality engineer.', 'Looking for devtool startups building testing or quality products.'],
  },
  {
    name: 'Luna Chen',
    email: 'seed-tester-76@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Luna Chen', bio: 'High school junior. Into robotics club, coding, and science fairs.', location: 'San Jose, CA' },
      narrative: { context: 'Looking for mentors and teammates for robotics or hackathons.' },
      attributes: { interests: ['robotics', 'coding', 'science fair', 'STEM'], skills: ['Python', 'Arduino', 'teamwork', 'presentations'] },
    },
    intents: ['Want to find teammates for robotics competitions or hackathons.', 'Looking for mentors in engineering or computer science.'],
  },
  {
    name: 'James Okonkwo',
    email: 'seed-tester-77@index-network.test',
    linkedin: 'https://linkedin.com/in/jamesokonkwo',
    github: 'https://github.com/jokonkwo',
    x: null,
    website: null,
    profile: {
      identity: { name: 'James Okonkwo', bio: 'Full-stack engineer with fintech and payments experience.', location: 'Lagos, NG' },
      narrative: { context: 'Building a payments product for African markets; need compliance and growth partners.' },
      attributes: { interests: ['fintech', 'payments', 'emerging markets'], skills: ['Node.js', 'Stripe', 'React', 'PostgreSQL'] },
    },
    intents: ['Seeking a compliance or legal co-founder for a payments startup in West Africa.', 'Looking for growth or marketing co-founders with local market knowledge.'],
  },
  {
    name: 'Emma Foster',
    email: 'seed-tester-78@index-network.test',
    linkedin: null,
    github: null,
    x: null,
    website: null,
    profile: {
      identity: { name: 'Emma Foster', bio: 'Swimming coach and former collegiate swimmer. Coaching age group and masters.', location: 'Seattle, WA' },
      narrative: { context: 'Looking for assistant coaches and pool or club partnerships.' },
      attributes: { interests: ['swimming', 'coaching', 'masters swimming', 'age group'], skills: ['stroke technique', 'workout design', 'meet management', 'parent communication'] },
    },
    intents: ['Want to find an assistant coach or volunteers for our swim team.', 'Looking for pool or club partnerships for clinics or camps.'],
  },
];
